version: '3.7'

services:

  database:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
      PGDATA: /var/lib/postgresql/data
      TZ: 'UTC'
      PGTZ: 'UTC'
    volumes:
      - ./database:/var/lib/postgresql/data

  server:
    depends_on:
      - database
    image: node
    volumes:
      - ./server:/server
    working_dir: /server
    command: bash -c "./wait-for-it.sh database:5432 -- node database/seed.js"
