version: '3.7'

services:

  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: database
      PGDATA: /var/lib/postgresql/data
      TZ: 'UTC'
      PGTZ: 'UTC'
    volumes:
      - ./database:/var/lib/postgresql/data

  server:
    image: node
    depends_on:
      - database
    volumes:
      - ./server:/server
    ports:
      - 3001:3001
      - 3002:3002
    working_dir: /server
    command: bash -c "DEBUG=server:* npm run start & node serverPicture.js"

  client:
    image: node
    depends_on:
      - server
    volumes:
      - ./client:/client
    ports:
      - 3000:3000
    working_dir: /client
    stdin_open: true
    command: bash -c "npm run start"
