  server:
    image: node
    volumes:
      - ./server:/server
    working_dir: /server
    command: bash -c "rm -rf node_modules/ && npm install"

  client:
    image: node
    volumes:
      - ./client:/client
    working_dir: /client
    command: bash -c "rm -rf node_modules/ && npm install"
    
  database:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
      PGDATA: /var/lib/postgresql/data
      TZ: 'UTC'
      PGTZ: 'UTC'
    volumes:
      - ./database:/var/lib/postgresql/data
